import { GraderMap } from "../src/grader";
import { SimpleMCGrader } from "../src/graders/common";

export const TF_Graders : GraderMap = {
  "sp20_mc_time_complexity_1" : new SimpleMCGrader(0),
  "sp20_mc_time_complexity_2" : new SimpleMCGrader(0),
  "sp20_mc_time_complexity_3" : new SimpleMCGrader(0),
  "sp20_mc_time_complexity_4" : new SimpleMCGrader(1),
  "sp20_mc_time_complexity_5" : new SimpleMCGrader(1),
  "sp20_mc_containers_and_templates_1" : new SimpleMCGrader(1),
  "sp20_mc_containers_and_templates_2" : new SimpleMCGrader(0),
  "sp20_mc_containers_and_templates_3" : new SimpleMCGrader(1),
  "sp20_mc_containers_and_templates_4" : new SimpleMCGrader(0),
  "sp20_mc_representation_invariants_1" : new SimpleMCGrader(1),
  "sp20_mc_representation_invariants_2" : new SimpleMCGrader(1),
  "sp20_mc_representation_invariants_3" : new SimpleMCGrader(0),
  "sp20_mc_representation_invariants_4" : new SimpleMCGrader(1),
  "sp20_mc_representation_invariants_5" : new SimpleMCGrader(0),
  "sp20_mc_dynamic_memory_1" : new SimpleMCGrader(0),
  "sp20_mc_dynamic_memory_2" : new SimpleMCGrader(1),
  "sp20_mc_dynamic_memory_3" : new SimpleMCGrader(1),
  "sp20_mc_dynamic_memory_4" : new SimpleMCGrader(1),
  "sp20_mc_dynamic_memory_5" : new SimpleMCGrader(1),
  "sp20_mc_dynamic_memory_errors_1" : new SimpleMCGrader(1),
  "sp20_mc_dynamic_memory_errors_2" : new SimpleMCGrader(1),
  "sp20_mc_dynamic_memory_errors_3" : new SimpleMCGrader(1),
  "sp20_mc_dynamic_memory_errors_4" : new SimpleMCGrader(0),
  "sp20_mc_dynamic_memory_errors_5" : new SimpleMCGrader(1),
  "sp20_mc_managing_dynamic_memory_1" : new SimpleMCGrader(1),
  "sp20_mc_managing_dynamic_memory_2" : new SimpleMCGrader(1),
  "sp20_mc_managing_dynamic_memory_3" : new SimpleMCGrader(1),
  "sp20_mc_managing_dynamic_memory_4" : new SimpleMCGrader(0),
  "sp20_mc_managing_dynamic_memory_5" : new SimpleMCGrader(1),
  "sp20_mc_big_three_1" : new SimpleMCGrader(0),
  "sp20_mc_big_three_2" : new SimpleMCGrader(1),
  "sp20_mc_big_three_3" : new SimpleMCGrader(1),
  "sp20_mc_big_three_4" : new SimpleMCGrader(1),
  "sp20_mc_big_three_5" : new SimpleMCGrader(0)
};

